In [ ]:
import numpy as np

pyList = [1001.5, 1003.2, 999.8, 1002.6, 1000.4, 999.1, 1002.9, 
          1001.3, 999.7, 1003.4, 1001.8, 1000.2, 999.5, 1002.7,
          1001.1, 999.4, 1003.3, 1001.6, 1000.1, 999.8, 985.2,
          984.5, 983.9, 986.1, 999.6, 1001.8, 1000.5, 999.2,
          1002.8, 1001.4, 999.9, 1003.1, 1001.7, 1000.3, 999.6,
          1002.5, 1001.2, 999.7, 1003.4, 1001.9, 985.4, 984.7,
          984.1, 986.3, 999.8, 1001.6, 1000.4, 999.3, 1002.9,
          1001.5, 999.8, 1003.2, 1001.7, 1000.2, 999.4, 1002.6,
          1001.3, 999.7, 1003.5, 1001.8, 985.1, 984.4, 983.8,
          986.2, 999.7, 1001.9, 1000.5, 999.1, 1002.7]

def PythonLists(pyList):

    print(pyList)# has commas 
    sumL = sum(pyList)
    print("The sum is: ",sumL)
    maxL = max(pyList)
    print("The maximum value is: ",maxL)
    minL = min(pyList)
    print("The minimum value is: ",minL)
    countL = len(pyList)
    print("The total number of values is:",countL)
    meanL = np.mean(pyList)
    print("The mean is: ",meanL)
    mean2L = np.average(pyList)
    print("The mean is: ",mean2L)
    print("\nTo sort a list in Python, First copy it ")
    sortL = pyList.copy()
    sortL.sort()
    print(sortL)
   
    
  
        
PythonLists(pyList)
print("\n----------------------------------------------------------------\n")







In [ ]:
import numpy as np
def PythonArrays():
    pyArr = np.array(pyList)
    print(pyArr) # has no commas, just spaces
    
    sumA = pyArr.sum()
    print("The sum is: ",sumA)
    maxA = pyArr.max()
    print("The maximum value is: ",maxA)
    minA = pyArr.min()
    print("The minimum value is: ",minA)
    countA = len(pyArr)
    print("The total number of values is: ",countA)
    meanA = pyArr.mean()
    print("The mean is: ",meanA)
    sortA = np.sort(pyArr)
    print("\nThe sorted array is: \n",sortA)
    medianA = np.median(pyArr)
    print(medianA)

PythonArrays()


In [1]:
import numpy as np
num_list = [12, 13, 14, 28, 29, 30, 41, 42, 43, 78, 79, 80,99,100,101]
print(num_list)

for i in range(0, len(num_list)):
    if i > 0 and num_list[i] != 0 :
        if (num_list[i + 1]) - num_list[i] > 1:
            num_list.insert(i + 1, 0)
           
            #list.insert(0, "FIrstWord")
print(num_list)    
group = np.array(num_list)

print(group)

first = group[0: ]
ch = np.where(group == 0)[0]
print(ch)
print("-------------------------------------------")





print("-------------------------------------------")
list_ind = []
sl = group[0:ch[0]:]
list_ind.append(list(sl))
print(sl,len(sl))


for j in range(0, len(ch)):
    if j +1 < len(ch):
        ss = group[ch[j]+1:ch[j+1]]
        list_ind.append(list(ss))
        print(ss, len(ss))
        
sm = group[ch[-1] + 1:]
list_ind.append(list(sm))
print(sm, len(sm)) 
    
print("-----------__________________________------------")   
print(list_ind)














[12, 13, 14, 28, 29, 30, 41, 42, 43, 78, 79, 80, 99, 100, 101]
[12, 13, 14, 0, 28, 29, 30, 0, 41, 42, 43, 0, 78, 79, 80, 0, 99, 100, 101]
[ 12  13  14   0  28  29  30   0  41  42  43   0  78  79  80   0  99 100
 101]
[ 3  7 11 15]
-------------------------------------------
-------------------------------------------
[12 13 14] 3
[28 29 30] 3
[41 42 43] 3
[78 79 80] 3
[ 99 100 101] 3
-----------__________________________------------
[[np.int64(12), np.int64(13), np.int64(14)], [np.int64(28), np.int64(29), np.int64(30)], [np.int64(41), np.int64(42), np.int64(43)], [np.int64(78), np.int64(79), np.int64(80)], [np.int64(99), np.int64(100), np.int64(101)]]


In [ ]:
listed = []
for i in range(0, len(transit_indixes) - 1):
    if i > 0 and transit_indixes[i] != 0 :
        if (transit_indixes[i + 1]) - transit_indixes[i] > 1:
            transit_indixes.insert(i + 1, 0) 
            group = np.array(transit_indixes)
            first = group[0:] 
            sep =  np.where(group == 0)[0] 
            if len(sep) == 0:
                return None 
            else: list_ind = [] 
            sl1 = group[0:sep[0]:]
            list_ind.append(list(sl1)) 
            for j in range(0, len(sep)): 
                if j + 1 < len(sep): 
                    ss = group[sep[j]+1:sep[j+1]] list_ind.append(list(ss)) sl = group[sep[-1] + 1:] list_ind.append(list(sl)) first = [] for i in range(0,len(list_ind)): firstIndex = list_ind[i][0] first.append(firstIndex) average = [] for i in range(0, len(first) - 1): diff = first[i + 1] - first[i] average.append(diff) final_average = np.mean(average) return final_average

In [ ]:
rdef analyze_transits(lightcurve, transit_indixes): listed = [] for i in range(0, len(transit_indixes) - 1): if i > 0 and transit_indixes[i] != 0 : if (transit_indixes[i + 1]) - transit_indixes[i] > 1: transit_indixes.insert(i + 1, 0) group = np.array(transit_indixes) first = group[0: ] sep =  np.where(group == 0)[0] if len(sep) == 0: list_dif = [] for i in range(0, len(transit_indixes)): list_dif.append(lightcurve[transit_indixes[i]]) depth = 1.0 - min(list_dif) duration = len(transit_indixes) tuple_1 = (round(depth,4),duration) tup_list = [] tup_list.append(tuple_1) return tup_list else: list_ind = [] sl1 = group[0:sep[0]:] list_ind.append(list(sl1)) for j in range(0, len(sep)): if j + 1 < len(sep): ss = group[sep[j]+1:sep[j+1]] list_ind.append(list(ss)) sl = group[sep[-1] + 1:] list_ind.append(list(sl)) tup_list = [] for row in list_ind: list_diff = [] for col in row: list_diff.append(lightcurve[col]) minn = min(list_diff) depth = 1.0 - minn duration = len(list_diff) tuple_fin = (round(depth,4),duration) tup_list.append(tuple_fin) return tup_list