In [1]:
import numpy as np

pyList = [1001.5, 1003.2, 999.8, 1002.6, 1000.4, 999.1, 1002.9, 1001.3, 999.7, 1003.4, 1001.8, 1000.2, 999.5, 1002.7, 1001.1, 999.4, 1003.3, 1001.6, 1000.1, 999.8, 985.2, 984.5, 983.9, 986.1, 999.6, 1001.8, 1000.5, 999.2, 1002.8, 1001.4, 999.9, 1003.1, 1001.7, 1000.3, 999.6, 1002.5, 1001.2, 999.7, 1003.4, 1001.9, 985.4, 984.7, 984.1, 986.3, 999.8, 1001.6, 1000.4, 999.3, 1002.9, 1001.5, 999.8, 1003.2, 1001.7, 1000.2, 999.4, 1002.6, 1001.3, 999.7, 1003.5, 1001.8, 985.1, 984.4, 983.8, 986.2, 999.7, 1001.9, 1000.5, 999.1, 1002.7]

arr = np.array(pyList)
print(arr)
print(5/2)
print(5//2 + 1)

print(arr[0:5//2 + 1])#2 1
print(arr[0:5//2 + 2])#2 2
print(arr[0:5//2 + 3])#2 3
print("------------------------------------------")
meanList = []
for i in range(1,5//2 + 2):
    meanList.append(arr[0:5//2 + i:1].mean())
 
print("--------------------------------------------")  
for i in range(1,  len(arr)- (5//2 )):
    meanList.append(arr[i: i + 5: 1].mean())


smoothArray = np.array(meanList)
print(smoothArray)

#print("\n----------------------------------------") 
#print(arr[len(arr) - (5//2 + 1): len(arr): 1])










[1001.5 1003.2  999.8 1002.6 1000.4  999.1 1002.9 1001.3  999.7 1003.4
 1001.8 1000.2  999.5 1002.7 1001.1  999.4 1003.3 1001.6 1000.1  999.8
  985.2  984.5  983.9  986.1  999.6 1001.8 1000.5  999.2 1002.8 1001.4
  999.9 1003.1 1001.7 1000.3  999.6 1002.5 1001.2  999.7 1003.4 1001.9
  985.4  984.7  984.1  986.3  999.8 1001.6 1000.4  999.3 1002.9 1001.5
  999.8 1003.2 1001.7 1000.2  999.4 1002.6 1001.3  999.7 1003.5 1001.8
  985.1  984.4  983.8  986.2  999.7 1001.9 1000.5  999.1 1002.7]
2.5
3
[1001.5 1003.2  999.8]
[1001.5 1003.2  999.8 1002.6]
[1001.5 1003.2  999.8 1002.6 1000.4]
------------------------------------------
--------------------------------------------
[1001.5        1001.775      1001.5        1001.02       1000.96
 1001.26       1000.68       1001.28       1001.82       1001.28
 1000.92       1001.52       1001.06       1000.58       1001.2
 1001.62       1001.1        1000.84        998.          994.24
  990.7         987.9         987.86        991.18        994.38
 

In [ ]:
import numpy as np
num1 = [1001.5, 1003.2, 999.8]
num2 = [1001.5, 1003.2, 999.8, 1002.6]
num3 = [1001.5, 1003.2, 999.8, 1002.6, 1000.4]
num4 = [1003.2, 999.8, 1002.6, 1000.4, 999.1]
num5 = [ 999.8, 1002.6, 1000.4, 999.1, 1002.9]
num6 = [1002.6, 1000.4, 999.1, 1002.9, 1001.3]

def firstSixAverages():
    avg1 = np.average(num1)
    avg2 = np.average(num2)
    avg3 = np.average(num3)
    avg4 = np.average(num4)
    avg5 = np.average(num5)
    avg6 = np.average(num6)

    print(avg1, avg2, avg3, avg4, avg5, avg6)


firstSixAverages()


nums1 = [1000.5, 999.1, 1002.7]
nums2 = [ 1001.9, 1000.5, 999.1, 1002.7]
nums3 = [ 999.7, 1001.9, 1000.5, 999.1, 1002.7]
nums4 = [986.2, 999.7, 1001.9, 1000.5, 999.1]



def lastSixAverages():
    last1 = np.average(nums1)
    last2 = np.average(nums2)
    last3 = np.average(nums3)
    last4 = np.average(nums4)
   

    print(last4, last3, last2, last1)

lastSixAverages()
