# Python basics week 3 (last week of half half recap)
today: numpy, arrays, slicing, pywhatkit, maybe pythonic code

In [6]:
! python -m pip install numpy
#command to install a library


[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy
import numpy as np
# from numpy import arrange

## Create arrays
array of elements has to be of the same datatype

In [3]:
import numpy as np
list = [1,5,8,10,3]
print(list)

array = np.array(list)
print(array)

print(list * 2) #list is seen as a whole, it will duplicate the list and paste itself behind the first occurence
print(array * 2) #treats every element separately to multiply

list.append(2)

#these 2 will give an error, because arrays have a fixed size!
#array.append(2) 
#array.add(2)




[1, 5, 8, 10, 3]
[ 1  5  8 10  3]
[1, 5, 8, 10, 3, 1, 5, 8, 10, 3]
[ 2 10 16 20  6]


In [4]:
import numpy as np

#1D arrays
#print(np.arrange(10))#--> fill an array with x numbers from 0 till x
print(np.zeros(10)) #--> fill an array with x 0's
print(np.ones(10))  #--> fill an array with x 1's
#print(np.twos(10))  -->

print(np.full(10,5)) #fill array with certain length with specific number(10 occurrences of 5)

print(np.random.randint(-5,6,10)) #--> remove the last digit and get only 1 number
print(np.random.random(10)) #x amount of random floats between 0 and 1


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 5 5 5 5 5 5 5 5 5]
[ 1  2 -4 -1  3 -4  3  0 -4 -2]
[0.62334115 0.07694341 0.46287991 0.85485182 0.18198791 0.96635585
 0.85386891 0.83380543 0.46734647 0.43946098]


## Reshaping & converting an array

In [5]:
import numpy as np
array = np.random.randint(-5,6,10)
print(array)
print(len(array)) #works but onlu i 1D
print(array.shape)
print(array.ndim)

#checking datatype
print(f"array is of datatype: {array.dtype}")

#conversions between types of arrays
arrayFloater = array.astype(float) #str int float
print(arrayFloater)

arrayString = array.astype("S")
print(arrayString)

# i - integer / b - boolean / f - float / M - datetime / S - string / but wording also works (float, str, int,...)
print()
#2D arrays
array2D = np.reshape(array, (2,5))
print(array2D)

print()
array2D = np.reshape(array, (5,2))
print(array2D)

print()
# has to perfectly fit
#array2D = np.reshape(array, (3,3))
#array2D = np.reshape(array, (4,3))
#print(array2D)

[-5  4  2  5  3 -4  1  2  4 -1]
10
(10,)
1
array is of datatype: int32
[-5.  4.  2.  5.  3. -4.  1.  2.  4. -1.]
[b'-5' b'4' b'2' b'5' b'3' b'-4' b'1' b'2' b'4' b'-1']

[[-5  4  2  5  3]
 [-4  1  2  4 -1]]

[[-5  4]
 [ 2  5]
 [ 3 -4]
 [ 1  2]
 [ 4 -1]]



## Slicing arrays
[start : end : step]
- start: number (index), included
- end: number (index), NOT included
- step: the size of a jump between values



In [6]:
import numpy as np

array = np.array([6, 8, 2, 9, 0, 1, 3, 5, 7, 4])
print(array)

# I want the first 4 numbers of the array
print(array[0:4:1])
print(array[0:4])
print(array[:4:])

# I want the 8 2 9 0
print(array[1:5:])

# I want the 8 9 
print(array[1:5:2])
print(array[1:4:2])

print(array[::]) # gives everything

#reverse
print(array[::-1])
print(array[-1::])

#slice the last 4, but don't use the positive index
print(array[-4::])
print(array[-1:0:-1]) #[4 7 5 3 1 0 9 2 8]
print(array[0:10:-1]) # prints nothing

[6 8 2 9 0 1 3 5 7 4]
[6 8 2 9]
[6 8 2 9]
[6 8 2 9]
[8 2 9 0]
[8 9]
[8 9]
[6 8 2 9 0 1 3 5 7 4]
[4 7 5 3 1 0 9 2 8 6]
[4]
[3 5 7 4]
[4 7 5 3 1 0 9 2 8]
[]


In [26]:
array = np.array([6, 8, 2, 9, 0, 1, 3, 5, 7, 4])
print(array)

print(array[0])# first
print(array[-1])
print(array[1])
median = np.median(array)
print(array[:4])

slice = array[2:7]
print(slice)
print("-------------------------------")

list = [2,3,6,2,7,7,23,31]
print(list)
first = list[:4]
print(first)

second = list[1:6]
print(second)

list.sort()
print(list)
print(list[len(list)//2]) # for odd length of list

median1 = list[len(list)//2]
median2 = list[len(list)//2 - 1 ] 
print(median2,median1)


[6 8 2 9 0 1 3 5 7 4]
6
4
8
[6 8 2 9]
[2 9 0 1 3]
-------------------------------
[2, 3, 6, 2, 7, 7, 23, 31]
[2, 3, 6, 2]
[3, 6, 2, 7, 7]
[2, 2, 3, 6, 7, 7, 23, 31]
7
6 7


### Exercise on slicing
we want to generate an array of the temperature measurements EVERY hour throughout a day.
(24 measurements) 
generate random temps: between 0 and 25 (use random ints)
--> use slicing to isolate periods and analyse them
- earlyBirdFeedsTheWorm: all temps first 6 hours of the day (includes the temp at 00:00 --> 06:00)
- everyoneAwakeBEFORENOON: 09:00 --> 13:00 (again the temps here)
- siesta: 14:00 - 16:00
- lateNightOwls: because they live in a different time, reverse the slice (LAST 4 MEARSURMENTS)
- trending: every 5 hours, starting at 00:00, 05:00, 10:00....


In [75]:
import numpy as np
import random

#temps = [random.randint(0,26) for x in range(24)]
#print(temps)

measurments  = np.random.randint(0,26,20)
print(measurments)

earlyBirdFeedsTheWorm = measurments[:7:]
print(earlyBirdFeedsTheWorm)

everyoneAwakeBEFORENOON = measurments[9:14:]
print(everyoneAwakeBEFORENOON)

siesta = measurments[14:17:]
print(siesta)

lateNightOwls = measurments[-1:-5:-1]
print(lateNightOwls)

trending = measurments[::5]
print(trending)





[12 21 22  9  4  1  9  1  2 20  2  9 10  1 20 19 13  6  3 16]
[12 21 22  9  4  1  9]
[20  2  9 10  1]
[20 19 13]
[16  3  6 13]
[12  1  2 19]


# Working with arrays

In [ ]:
import numpy as np

a = np.arange(0,10)
b = np.arange(9, -1, -1)
print(a,b)

print(a + b)
print(a - b)
print(a * b)

print(np.where(a % 2 == 0, a + 5, a))
print(np.where(a % 2 == 0))

array = np.where(a % 2 == 0)
print(array[0]) # the regular np.where with only a condition and no True or False, returms a tuple with the indexes 
# of the values where the condition is met.

print(np.where(b > 5))
meetingCondition = np.where(b > 5)[0]
print(meetingCondition)

b = np.reshape(b, (2,5))
print(b)
print()
print(b.sum(axis = 0)) # the sum of all columns each counted up together
print(b.sum(axis = 1)) # sum of each row
print(b.cumsum(axis = 1))

print()
print(a.sum())
print(a.min())
print(a.max())

print(np.sqrt(a)) # square root of each number in a
print(np.sqrt(a.max()))


[0 1 2 3 4 5 6 7 8 9] [9 8 7 6 5 4 3 2 1 0]
[9 9 9 9 9 9 9 9 9 9]
[-9 -7 -5 -3 -1  1  3  5  7  9]
[ 0  8 14 18 20 20 18 14  8  0]
[ 5  1  7  3  9  5 11  7 13  9]
(array([0, 2, 4, 6, 8]),)
[0 2 4 6 8]
(array([0, 1, 2, 3]),)
[0 1 2 3]
[[9 8 7 6 5]
 [4 3 2 1 0]]

[13 11  9  7  5]
[35 10]
[[ 9 17 24 30 35]
 [ 4  7  9 10 10]]

45
0
9
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
3.0


In [18]:
import this 


The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [20]:
! python -m pip install pywhatkit

     ---------------------------------------- 0.0/61.2 kB ? eta -:--:--
     ------ --------------------------------- 10.2/61.2 kB ? eta -:--:--
     ---------------------------------------- 61.2/61.2 kB 1.1 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
  Using cached requests-2.32.5-py3-none-any.whl.metadata (4.9 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
  Using cached jinja2-3.1.6-py3-none-any.whl.meta

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


  Using cached pywhatkit-5.4-py3-none-any.whl.metadata (5.5 kB)
  Using cached pillow-12.1.1-cp311-cp311-win_amd64.whl.metadata (9.0 kB)
  Using cached pyautogui-0.9.54-py3-none-any.whl
  Using cached requests-2.32.5-py3-none-any.whl.metadata (4.9 kB)
  Using cached wikipedia-1.4.0-py3-none-any.whl
  Using cached flask-3.1.3-py3-none-any.whl.metadata (3.2 kB)
  Using cached blinker-1.9.0-py3-none-any.whl.metadata (1.6 kB)
  Using cached click-8.3.1-py3-none-any.whl.metadata (2.6 kB)
  Using cached itsdangerous-2.2.0-py3-none-any.whl.metadata (1.9 kB)
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
  Using cached markupsafe-3.0.3-cp311-cp311-win_amd64.whl.metadata (2.8 kB)
  Using cached werkzeug-3.1.6-py3-none-any.whl.metadata (4.0 kB)
  Using cached pymsgbox-2.0.1-py3-none-any.whl.metadata (4.4 kB)
  Using cached pytweening-1.2.0.tar.gz (171 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements t

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
import pywhatkit
#pywhatkit.playonyt("Jake Paul")
pywhatkit.sendwhatmsg("+32465315544","Hey Joseph, this is another test, kind regards, YOUR STALKER",
                      16, 38, 15, True, 2)

In [6]:
import pywhatkit


num = 5
while num != 100:
    pywhatkit.playonyt("Zuba Ray - Everyday ft Nel Ngabo")
    num += 5




In [ ]:
import pywhatkit

pywhatkit.playonyt("")
   


'https://www.youtube.com/watch?v=PKZedna2Yt4\\\\u0026pp=ygUUUGFzdG9yIE1hcmsgQW1hbmt3YWg%3D'

In [4]:
import pywhatkit

pywhatkit.sendwhatmsg("+32466013636","Hey Law!!\nThis text wasn't written by your brother.",21,18, 15, True, 5)

In 24 Seconds WhatsApp will open and after 15 Seconds Message will be Delivered!


In [1]:
import pywhatkit

pywhatkit.sendwhatmsg("+32467899458","Hey Orda!!\nNice to meet you xoxo.",16,20, 15, True, 5)

In 57 Seconds WhatsApp will open and after 15 Seconds Message will be Delivered!


In [1]:
print("Hello")

Hello


In [ ]:
+32 467 89 94 58